# Generated by Django 4.2.26 on 2026-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0113_merge_20251209_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimeta',
            name='job_type',
            field=models.TextField(default='developer.nlr.gov'),
        ),
    ]
