# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0016_alter_erpmeta_reopt_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmeta',
            name='job_type',
            field=models.TextField(default='developer.nlr.gov'),
        ),
    ]
